version: '3.7'

services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm start
    volumes:
      - '.:/app:cached'
      - '/app/node_modules'
    ports:
      - 9001:9001
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CI=true
    command: npm test
